[build]
  command = "pip install -r requirements.txt"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.9"

[dev]
  command = "python hr_dashboard_web.py"
  port = 5000
  publish = "."

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
