services:
  - type: web
    name: hr-analytics-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn hr_dashboard_web:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true
